#!/bin/bash

set -e

# Define set of base Environment variables
export APP_PORT=${APP_PORT:-80}
export APP_ENV=${APP_ENV:-local}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-root}
export DB_NAME=${DB_NAME:-arena}
export DB_USER=${DB_USER:-arena}
export DB_PASS=${DB_PASS:-root}

# Set regular expression for repository
HTTPSREGEX="^https?://"

# Check if site already exists. 
# Remove site if found
if [ -d "site" ]; then
    rm -rf site
    rm -rf build/storage
fi

./develop down

# Ask for the git repository url.
# Should be https://....
# Clone repository if it can find one
echo -n "Enter the url of the git repsoitory you would like to clone: "
read REPOSITORY
if [[ $REPOSITORY =~ $HTTPSREGEX ]]; then

    git clone -b production $REPOSITORY site
else 
    echo "We didn't like that input. Exiting..."
    exit 1
fi

# Generate an environment file for Laravel
echo "Creating a env file..."
  	cat >> site/.env <<EOL
#################################################
# APP ENVIRONMENT SETTINGS
#################################################
APP_ENV=local
APP_DEBUG=true
APP_TIMEZONE=Australia/Sydney
APP_KEY=
APP_URL=http://arena.local
APP_COUNTRY=AU
APP_CURRENCY=AUD

#################################################
# DB SETTINGS
#################################################
DB_DATABASE=arena
DB_USERNAME=root
DB_PASSWORD=root
DB_HOST=mysql
DB_PORT=3306

COREDB_DATABASE=coredb
COREDB_USERNAME=root
COREDB_PASSWORD=root
COREDB_HOST=mysql
COREDB_PORT=3306

VOIPDB1_DATABASE=2talk
VOIPDB1_USERNAME=root
VOIPDB1_PASSWORD=root
VOIPDB1_HOST=mysql
VOIPDB1_PORT=3306

#################################################
# DRIVER SETTINGS
#################################################
CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=redis
BROADCAST_DRIVER=log
LOG_CHANNEL=single

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

#################################################
# TESTING CODES
#################################################
SP_TEST=100
WL_CREDIT_CARD_DEFAULT=100
EOL

docker network create nginx-proxy

# Install composer on the backend
./develop composer install

sleep 5

# Generate a key for laravel
./develop art key:generate

 sleep 5

# Install npm on the node server
./develop npm install

sleep 5

# Run the development script for npm to compile assets
./develop npm run dev

# Make missing directories for laravel
# Otherwise we receive a cache path issue
mkdir site/storage
mkdir site/storage/framework
mkdir site/storage/framework/sessions
mkdir site/storage/framework/views
mkdir site/storage/framework/cache

# Starting app, mysql, nginx and proxy...
./develop up -d app mysql scheduler redis proxy

sleep 5

# Check that we can connect to the local database
until ./develop exec mysql mysql -h 127.0.0.1 -u $DB_USER -p$DB_PASS -D $DB_NAME --silent -e "show databases;"
do
  echo "Waiting for database connection..."
  sleep 5
done

echo "Successfully connected to the database..."

# Ask if migrations need to be run
# Sometimes we don't want to re run these if storage folder is still intact
echo -n "Do you want to run migrations? (Y/N) "
read MIGRATIONS
if [[ $MIGRATIONS = 'Y' ]]; then

    if [ $DB_PASS = 'root' ];
    then
        echo Database Migration Started!
       
        # Run migrations
        ./develop art migrate --path="database/migrations/db-calldetails";
        ./develop art migrate --path="database/migrations/db-coredb";
        ./develop art migrate --path="database/migrations/db-arena";
        ./develop art migrate --path="database/migrations/db-2talk";
        echo Database Migration Finished!

        sleep 5

        # Run Seeds
        echo Database Seeding Started!
        ./develop art db:seed --class=ConfigSeeder;
        ./develop art db:seed --class=WhiteLabelSeeder;
        ./develop art db:seed --class=CustomerSeeder;
        ./develop art db:seed --class=NumberClassSeeder;
        ./develop art db:seed --class=LineNumberAvailableDatabaseSeeder;
        ./develop art db:seed --class=DeviceProvisionSeeder;
        ./develop art db:seed --class=CallDetailsToBillDatabaseSeeder;
        ./develop art db:seed --class=UserSeeder;
        echo Database Seeding Completed!
    fi

fi

# Boot up queue once migrations and seeds are complete.
# Can receive errors if done before migrations
echo Starting queue...
./develop up -d queue

#Set up https at https://arena.local
./develop npm i -g create-ssl-certificate

mkdir ./build/config/nginx/
cd ./build/config/nginx/certs && create-ssl-certificate --hostname arena --domain local

mv ssl.crt arena.local.crt
mv ssl.key arena.local.key

echo Installation Complete!