version: "2"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: laravel-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/vhost.d:/etc/nginx/vhost.d
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - ./config/nginx/html:/usr/share/nginx/html
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/nginx/vhost.d:/etc/nginx/vhost.d
      - ./config/nginx/certs:/etc/nginx/certs:rw
      - ./config/nginx/html:/usr/share/nginx/html
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      VIRTUAL_HOST: arena.test
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: [arena.test]
      LETSENCRYPT_EMAIL: jackson@yourcloudtelco.com
    links:
      - mysql
      - redis
    expose:
      - 80
  scheduler:
    extends:
      file: docker-compose.base.yml
      service: scheduler
    depends_on:
      - app
      - mysql
      - redis
    environment:
      CONTAINER_ROLE: scheduler
  queue:
    extends:
      file: docker-compose.base.yml
      service: queue
    depends_on:
      - app
      - mysql
      - redis
    environment:
      CONTAINER_ROLE: queue
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_PORT}:3306"
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"